### ISSUE TITLE
Accidental Digestion doesn't work with animals

### ISSUE THREAD

**Issue by BoringKobold** [Error-String-Expected-Got-Nil/RV2-Esegn-Additions#1] opened 2024-08-22 07:03 UTC
Accidental digestion doesn't work with animals, im unsure as to why, but trying to just results in the prey getting permenatly stuck in the  "warm up" phase, as can be seen in the attached screen shot, it works fine with pawns, but animals dont work

![image](https://github.com/user-attachments/assets/ce24b21d-473f-49e5-a0bb-a8004d7b07ba)

**Comment by BoringKobold** [comment] 2024-08-22 17:33
forgot to include, that when the warm up phase reaches 100% it gives another "accidentally Digesting: animal", and says "X pawn is accidentally digesting animal"  and as far as im aware, it will not stop and the list will grow indefinetly

**Comment by Error-String-Expected-Got-Nil** [comment] 2024-08-22 18:06
Huh, that is a weird one... have you found any way to make this occur repeatably? There's a dev tool to force it to start. It might be a little while before I can investigate this but I'll look into it when I get a chance. Any details you can get would help, especially what errors are in the log, if any.

**Comment by BoringKobold** [comment] 2024-08-22 18:08
it ALWAYS happens with animals, i dont have to do anything special, just when i pawn tries digesting animals through accidental digestion it never actually starts digesting them, ill see if an error pops up, but i dont there will be one, i didnt see any last night
(i dont know what i would be looking for anyway)

**Comment by BoringKobold** [comment] 2024-08-22 18:14
while i get this error log, im going to see if perhaps some settings are causing issues, though i dont know why they would

**Comment by Error-String-Expected-Got-Nil** [comment] 2024-08-22 18:14
Hmm, alright then. If I can replicate this I'll figure out what causes it and put the patch out probably by tomorrow, we'll see.

**Comment by BoringKobold** [comment] 2024-08-22 18:19
![image](https://github.com/user-attachments/assets/44f16f78-977c-4278-b456-355336e68cc1)
god its so inconsistent, while trying to get the error logs (not the one attachted), it fucking worked and switched phases into the digest phase

**Comment by Error-String-Expected-Got-Nil** [comment] 2024-08-22 18:24
That error is what I want- click on it and it will show a bunch of extra text in a bottom tab, copy/paste or screenshot whatever is in there. You can drag the top part of the tab to expand it.

**Comment by Error-String-Expected-Got-Nil** [comment] 2024-08-22 18:32
Hmmm... that would be what I want, but it doesn't have any useful information. Whatever caused that, the error was purely in RV2- but most likely the error is only due to whatever is going wrong in my code.

I'll probably just have to try and replicate this myself. You can get it to happen by just having a pawn endo an animal and starting accidental digestion?

**Comment by BoringKobold** [comment] 2024-08-22 18:34
yep, either forcing it through dev, or letting it happen naturally, one thing ive noticed that sometimes reloading may let them actually digest the animal? though the reload has been done when it first started the accidental digestion

**Comment by Error-String-Expected-Got-Nil** [comment] 2024-08-22 18:39
It could be a save/load issue, most of the initial bugs were related to that, but I'll have to look into to say more.

**Comment by BoringKobold** [comment] 2024-08-22 18:41
so what i said about it working for pawns was false
![image](https://github.com/user-attachments/assets/2fbcfc92-8ff2-4a4a-93f8-fa2cdddff2ab)

**Comment by Error-String-Expected-Got-Nil** [comment] 2024-08-22 18:46
Hmm. Yeah, that makes more sense- animals *are* pawns and should be treated the same, though this being a more widespread bug is concerning.

What exactly do you do to cause this? Does it involve a save/load at a particular time? Sending me your save file would also help a bit.

**Comment by BoringKobold** [comment] 2024-08-22 18:47
this does not include any save/load at anytime, infact, a save/load seems to sometimes, FIX the issue, tho not always

i will send my save file, if i can figure out how. should i also send my mod list?

**Comment by Error-String-Expected-Got-Nil** [comment] 2024-08-22 18:52
Possibly, so would checking if this still happens with a stripped-down modlist, if you can do that. You can DM it on discord, save file should be located at %appdata%/../LocalLow/Ludeon Studios/RimWorld by Ludeon Studios/Saves (assuming you're on Windows, paste that into the file explorer's directory bar at the top)

**Comment by BoringKobold** [comment] 2024-08-22 18:54
im currently using RimPy to make a "pack" to give to you, this should include all the setting modificitations i have done to the mods through the mod settings, is that ok?

**Comment by Error-String-Expected-Got-Nil** [comment] 2024-08-22 18:57
Ah... okay, nevermind. I just tried it and made the bug happen on the first try. I didn't test the original version well enough, it seems. I don't have time to fix this right now but I should be able to later. Slightly awkward that it actually just didn't work at all and it took this long to notice...

**Comment by BoringKobold** [comment] 2024-08-22 18:58
lol, well atleast its easy to get to happen, and hopefully will be an easy fix

**Comment by Error-String-Expected-Got-Nil** [comment] 2024-08-22 19:03
I actually think I just figured out what the problem is, but I don't think I have enough time to solve it right now. It should be a fairly easy fix though, so I'll probably have it out later tonight.

**Comment by BoringKobold** [comment] 2024-08-22 19:04
awesome, thank you

**Comment by Error-String-Expected-Got-Nil** [comment] 2024-08-22 19:23
Actually, there is one more thing you could do to help me verify it while I'm away from my computer- does it still happen if you disable path conflicts in my mod's settings?

**Comment by BoringKobold** [comment] 2024-08-22 19:40
it appears it has, though i only did it twice, but overall yes, it seems that it has

**Comment by Error-String-Expected-Got-Nil** [comment] 2024-08-22 19:56
Cool, I'm probably right about where the issue is then. Appreciated!

**Comment by Error-String-Expected-Got-Nil** [comment] 2024-08-23 00:40
Fixed with latest release. Quite literally a one-liner, but I didn't have enough time to sit down at my computer and verify it until now. 

When path conflicts and accidental digestion are enabled, eaten pawns will be added to a particular accidental digestion event if possible... but the check for that didn't make sure the vore record wasn't already being tracked for accidental digestion. Now it does that, bug should be fixed. I really should have noticed that one sooner.

**Closed by Error-String-Expected-Got-Nil** 2024-08-23 00:40 UTC
